eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://mysql-dbinstance.cxkk8oa6ejmy.us-east-1.rds.amazonaws.com:3306/userdb
    password: Jamesbond007;
    username: admin
