eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb+srv://kesavnallan:Swordfish@atlas-cluster.rp4ne.mongodb.net/orderdb
      host: atlas-cluster-shard-00-00.rp4ne.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true 