apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-dbinstance.cxkk8oa6ejmy.us-east-1.rds.amazonaws.com/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-dbinstance.cxkk8oa6ejmy.us-east-1.rds.amazonaws.com/foodcatalogdb
  userdb_url: jdbc:mysql://mysql-dbinstance.cxkk8oa6ejmy.us-east-1.rds.amazonaws.com/userdb
  orderdb_url: mongodb+srv://kesavnallan:Swordfish@atlas-cluster.rp4ne.mongodb.net/orderdb/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka
  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  