apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogapp
  labels:
    app: foodcatalogapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogapp
  template:
    metadata:
      labels:
        app: foodcatalogapp
    spec:
      containers:
        - name: foodcatalogapp
          image: seekeshav/food-catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: foodcataloguedb_url
---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalog-service
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: foodcatalogapp
 
